version: '3.9'

services:
  todo-app:
    container_name: persons-app
    build: 
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - todo-backend
    restart: unless-stopped

  postgres:
    container_name: persons-db
    image: postgres:latest
    hostname: postgres
    env_file: 
      - .env
    ports:
      - "${LOCAL_DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - todo-backend

networks:
  todo-backend:
    driver: bridge

volumes:
  pg-data:
  