http:
  host: command
  port: 8080
  shutdownTimeout: 5s
  readTimeout: 5s
  writeTimeout: 5s

db:
  maxOpenConns: 5
  maxIdleConns: 5
  connMaxIdleTime: 5m
  connMaxLifetime: 5m

project:
  name: command
  level: debug

client:
  timeout: 5s